### ISSUE TITLE
Issues encountered with the WoE Calculate Response tool

### ISSUE THREAD

**Issue by DarthSysmon** [gtkfi/ArcSDM#12]
I am running the same model space in two ArcMap 10.2 sessions. One with the old SDM and one with the new version.

1) weights tables within the ArcMap ToC cannot be dragged to the Input weights tables window, but have to be loaded from disc. In the old version, one can at least select tables loaded to the workspace in the dropdown menu. See attached image.
![calculateresponse_oldversion](https://cloud.githubusercontent.com/assets/25653028/22954213/045c1034-f37a-11e6-9dc6-5730b44a849b.PNG)

2) All output raster names are autoloaded as "[nameoffirstrasterloaded]_CalculateResponse.tif". In the old version, the names come up as %WORKSPACE%\W_pprb for post prob raster, W_Std for Std Dev raster, etc. The correct suffixes should be at least spelled out in the help file/tooltip.

2b) Output MD variance raster and Output Total Std Deviation Raster fields appear to expect .dbf endings, so dbf table outputs rather than rasters.

3) Grid names need to be shorter than 13 characters. Not a new issue, and really a non-issue.

**Comment by DarthSysmon** [comment]
4.  Fatal crash due to missing MDvar raster. Due to the MDvar (and probably tstd) raster fields outputting dbf tables, the script crashes when executing MissingDataVar_Func.
[CalculateResponseCrash.txt](https://github.com/gtkfi/ArcSDM/files/775643/CalculateResponseCrash.txt)

**Comment by trotor** [comment]
1) This seems to be Arcmap issue - I will report it to ESRI asap. You can
drag and drop them from arccatalog window however, no need to use ... button
2) Will take a look at this and make it like it was. I believe I saw these
names somewhere and assumed they are the ones to be used.
2b) This is odd. Will take a look and open new issue for this if needed.
Helps us organizing work.

3) There is no neeed to limit the namesize for files in filegeodatabase
(one of the good reasons) so this is obviously a bug for them.  Will fix.

**Comment by trotor** [comment]
Will fix this.

**Comment by trotor** [comment]
Hi, this and the crash could be now fixed in 5.00.07 version. We are
checking if the calculations come out correctly as this needed some
workarounds for missing old functions.

i will respond the same in all related bug reports.

T

**Comment by DarthSysmon** [comment]
Hi there,

Ran the same model with the v7 toolbox. Calculate Weights still seems to be unable to handle missing data (-99), and Calculate Response still crashes due to two of the output grids being erroneously set to dbf table format instead. Dump of the Calculate Response crash attached.

Cheers,
S
[CalculateResponseCrash5.00.07.txt](https://github.com/gtkfi/ArcSDM/files/786227/CalculateResponseCrash5.00.07.txt)

**Comment by trotor** [comment]
I will take closer look on that crash today. I also opened new issue for calculate weights so I don't get confused on which is which: https://github.com/gtkfi/ArcSDM/issues/20

**Comment by trotor** [comment]
Also .dbf endings for rasters fixed, (#21)

**Comment by DarthSysmon** [comment]
The .dbf endings have been fixed, thank you. The file names still come out as .tif, but the paths stay where they should be when I change them to what I need them to be, and with endings of _pprb, _std, _MDvar, _tstd, and _conf.

The tool still crashes when beginning to make the MDvar raster: Error 010240L Could not save raster data set to [path] without output format GRID.
[CalculateResponseCrash5.00.08.txt](https://github.com/gtkfi/ArcSDM/files/788846/CalculateResponseCrash5.00.08.txt)

Leaving the .tif format, but otherwise replacing the file name with the proper raster labels make no difference.

![v8_crissue_tifoutput](https://cloud.githubusercontent.com/assets/25653028/23147251/6b19cc18-f842-11e6-9ce3-4a5c9505089c.PNG)

**Comment by trotor** [comment]
Hi, could you explain why you want to have all the output rasters with same name or does the tool do that for some reason? I might have not understood what is missing?

**Comment by DarthSysmon** [comment]
Hi Tero. I don't want the output rasters to have the same name. But the Calculate Response tool adds what you see in the image by default. I have to then manually rename everything to [modelname]_pprb and so on.

**Comment by trotor** [comment]
Aaa, ok, I will take a look at that. It shouldn't.

**Comment by trotor** [comment]
Hi, I can't replicate this renaming to ...CalculateResponse.tif error - could you explain the steps how to reproduce this?

**Comment by DarthSysmon** [comment]
1) Open model workspace with SDM tool installed. I run ArcMap 10.2.
2) Open Calculate response from Weights of Evidence toolbox in ArcToolbox.
3) Drop (or open, or select from dropdown) an Input Raster Layer. Or several.

The last five fields (Output post probability raster, Output standard deviation raster, etc) then autopopulates with "[the name of the (first) Input Raster Layer]_CalculateResponse.tif".

**Comment by trotor** [comment]
![image](https://cloud.githubusercontent.com/assets/10844537/23296010/e297d6d2-fa7b-11e6-8589-40792fe21a3b.png)


I can't replicate this on 10.4.1 - perhaps it is 10.2 issue? Do you have opportunity to try it on newer version?

**Comment by DarthSysmon** [comment]
Tested it with 10.4.0 and the naming works fine, just as in your example above. 

Cheers,
S

**Comment by trotor** [comment]
I am closing this issue, and focusing on the missing data issue. Thanks for the testing!

(Multiple issues spead to new issues for easier tracking)
