### ISSUE TITLE
Grand Wofe error

### ISSUE THREAD

**Issue by VesaNy** [gtkfi/ArcSDM#85]
Grand Wofe fails to run. I am running it with some demo data (see below). Tried to run in a model or as a tool.

Executing: GrandWofe GW1 lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co c;o;o;o;o;o orogenic_au_80 # 2 1
Start Time: Mon Apr 23 12:33:55 2018
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.00.28 for ArcGis (Pro and Desktop)

ArcGis version:      Desktop 10.4.1
Workspace:           C:\arcsdm\training\demo.gdb (LocalDatabase)
Scratch workspace:   C:\arcsdm\training\demo.gdb (LocalDatabase)
Map Units:           meter
Mask:                "study_area.shp" and it is FeatureLayer
Mask size:           98856.9550016
Cell Size:           500
# Training Sites:    32
Unit Cell Area:      1.0km^2, Cells in area: 98856.9550016 
Prior Probability:   0.000324
Training Set:        C:\ArcSDM5\Test\orogenic_au_80.shp
Study Area Raster:   C:\ArcSDM5\Data\DemoData_version_files\shape_files\study_area.shp
Study Area Area:     98856.9550016km^2
========== Starting GrandWofe ====================
 
---------- Preparing data ------------
Running Calculate weights for lithoname200k (c)...
========== Calculate weights ==========
Creating table:      C:\arcsdm\training\demo.gdb\lithoname200k_GW1_CT (Categorical)
GP ERRORS:
ERROR 999999: Error executing function.
Unexpected operation [GDB_Items]
The table was not found. [Extr11Tmp]
ERROR 010024: Error during conversion.
Failed to execute (ExtractValuesToPoints).

PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM5\Toolbox\arcsdm\workarounds_93.py", line 62, in ExtractValuesToPoints
    gp.ExtractValuesToPoints_sa(inputFeatures, inputRaster, tempExtrShp)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: ERROR 999999: Error executing function.
Unexpected operation [GDB_Items]
The table was not found. [Extr11Tmp]
ERROR 010024: Error during conversion.
Failed to execute (ExtractValuesToPoints).

Calculate weights caught arcpy.ExecuteError: 
Failed to execute. Parameters are not valid.
ERROR 000735: Input Table: Value is required
Failed to execute (Statistics).

-------------- END EXECUTION ---------------
GP ERRORS:
Failed to execute. Parameters are not valid.
ERROR 000735: Input Table: Value is required
Failed to execute (Statistics).

PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM5\Toolbox\arcsdm\grand_wofe_lr.py", line 141, in execute
    Missing_Data_Value)

Error Info:
    (<class 'arcgisscripting.ExecuteError'>, ExecuteError(), <traceback object at 0x3941A738>)

Traceback (most recent call last):
  File "<string>", line 151, in execute
  File "C:\ArcSDM5\Toolbox\arcsdm\grand_wofe_lr.py", line 141, in execute
    Missing_Data_Value)
  File "C:\ArcSDM5\Toolbox\arcsdm\calculateweights.py", line 655, in CalculateWeights
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (GrandWofe).
Failed at Mon Apr 23 12:33:57 2018 (Elapsed Time: 1,90 seconds)

**Comment by tachyon-work** [comment]
This is specifically to do with the python script dropping the .dbf extension for the weights table in the GrandWofe script. It needs to be explicitly added back in. Make sure the python script you're using includes the  ".dbf" bit for the table filename in the script. If you don't include it, the script won't read it as a table and thinks it's invalid. This is explicitly required in GrandWofe because you're not specifying the output filenames in the user interface, it's being done behind the scenes in the script.

I fixed this in the version I sent your team in January, is there a reason that these script fixes have not been integrated and put on github?

Also, I noticed that you are using a shapefile for your raster mask here. Is that intentional?

**Comment by trotor** [comment]
Thank you for your bug report and thanks for replying Tachyon! 

I have been waiting for feedback from the testgroup on the bugs and haven't known this bug to exist anymore. And sincere apologies! I have missed the script fix, where did you send it? It would be very good to have you as part of the team here so you could just send pull request to github. We are trying to be open source collaboration project but perhaps I am missing some settings on the repository?

I will try to reproduce and fix this bug today. 

(Btw, is this bug related to those four other bugs about grand wofe waiting for response?)

**Comment by VesaNy** [comment]
I tried to use a grid as a mask but it failed so I changed it to a shape file. Maybe that is a bug as well. Did not have time to test with another. I will try it now and let you know.

**Comment by tachyon-work** [comment]
I have a functioning version. Let me try and upload it to Github.

**Comment by trotor** [comment]
Raster mask (or whatever type failing without error text) not working is a bug, I will create new one for that one for you.

**Comment by tachyon-work** [comment]
@trotor Can you give me upload permission? I have a working version. ![image](https://user-images.githubusercontent.com/32659237/39168545-645b8410-47e8-11e8-8d70-bde71f8d63fb.png)

**Comment by trotor** [comment]
I added you as collaborator, try if that works?

**Comment by tachyon-work** [comment]
Email came through with the permissions eventually :) Uploaded a zip file with the version we've been using internally at Kenex since January. As far as we can tell we've got a functioning version of the WofE toolbox. Been tested in 10.3 and 10.5.

**Comment by trotor** [comment]
Thank you! Too bad I didn't get this on january - it would have been great relieve for stress :)

I think after I set you as collaborator you can now comment and close the issues you think should have been fixed.

**Comment by tachyon-work** [comment]
Great, thanks :)

Will go back and close a few things I think.

 Assume I will probably see you both next week in Rovaniemi. Let me know if you run into any issues with the code, but I think I commented my changes in the relevant files.

**Comment by VesaNy** [comment]
Running with the new script but the problem remains. I will give a new try with a clean project just to be sure there is nothing hanging.
Here the errors:

Executing (Grand WOFE): GrandWofe GW2 lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co c;o;o;o;o;o orogenic_au_80 # 2 1
Start Time: Tue Apr 24 10:48:54 2018
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.00.28 for ArcGis (Pro and Desktop)

ArcGis version:      Desktop 10.4.1
Workspace:           C:\arcsdm\training\work (FileSystem)
Scratch workspace:   C:\arcsdm\training\scratch (FileSystem)
Map Units:           meter
Mask:                "study_area_g" and it is RasterLayer
Mask size:           98850.5
Cell Size:           500
# Training Sites:    32
Unit Cell Area:      1.0km^2, Cells in area: 98850.5 
Prior Probability:   0.000324
Training Set:        C:\ArcSDM5\Test\orogenic_au_80.shp
Study Area Raster:   C:\ArcSDM5\Data\DemoData_version_files\derivatives\study_area_g
Study Area Area:     98850.5km^2

========== Starting GrandWofe ====================
 
---------- Preparing data ------------
Running Calculate weights for lithoname200k (c)...
========== Calculate weights ==========
Creating table:      C:\arcsdm\training\arcsdm\training\work\lithoname200k_GW2_CT.dbf (Categorical)


Calculate weights caught arcpy.ExecuteError: 
Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset C:\arcsdm\training\arcsdm\training\work\lithoname200k_GW2_CT.dbf does not exist or is not supported
Failed to execute (AddField).

-------------- END EXECUTION ---------------
GP ERRORS:
Failed to execute. Parameters are not valid.
ERROR 000732: Input Table: Dataset C:\arcsdm\training\arcsdm\training\work\lithoname200k_GW2_CT.dbf does not exist or is not supported
Failed to execute (AddField).


PYTHON ERRORS:
Traceback Info:
  File "C:\ArcSDM5\Toolbox\arcsdm\grand_wofe_lr.py", line 141, in execute
    Missing_Data_Value)

Error Info:
    (<class 'arcgisscripting.ExecuteError'>, ExecuteError(), <traceback object at 0x388D93C8>)

Traceback (most recent call last):
  File "<string>", line 149, in execute
  File "C:\ArcSDM5\Toolbox\arcsdm\grand_wofe_lr.py", line 141, in execute
    Missing_Data_Value)
  File "C:\ArcSDM5\Toolbox\arcsdm\calculateweights.py", line 655, in CalculateWeights
    raise arcpy.ExecuteError;
ExecuteError

Failed to execute (Grand WOFE).
Failed at Tue Apr 24 10:49:00 2018 (Elapsed Time: 5,86 seconds)

**Comment by trotor** [comment]
I think you are still running wrong version (from the version info on top)

Download mergetmp branch or use Tachyon's zip.

**Comment by tachyon-work** [comment]
I'm downloading the demo data onto my laptop. Let me see what happens. GrandWofE worked at work with our data.

**Comment by tachyon-work** [comment]
Success. You will however see why I am not a fan of using the "ordered" type for GrandWofE and why I modified the code to let the user specify ascending or descending :) I terminated the process but you can see it's working:

```
Executing: GrandWofe gw1 lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co c;o;o;o;o;o Orogenic_Au # 2 1
Start Time: Tue Apr 24 20:18:43 2018
Running script GrandWofe...

========== arcsdm values  ==========
                     ArcSdm 5.00.24 for ArcGis (Pro and Desktop)

Workspace:           C:\Users\arianne\Desktop\sdm (FileSystem)
Scratch workspace:   C:\Users\arianne\Desktop\sdm\tmp (FileSystem)
Map Units:           meter
Mask:                "lithoname200k" and it is RasterLayer
Mask size:           98843.25
Cell Size:           500
# Training Sites:    40
Unit Cell Area:      1.0km^2, Cells in area: 98843.25 
Prior Probability:   0.000405
Training Set:        C:\Users\arianne\Desktop\Arianne data\ArcSDM_Demodata\data\DemoData_version_files\shape_files\Orogenic_Au.shp
Study Area Raster:   C:\Users\arianne\Desktop\Arianne data\ArcSDM_Demodata\data\DemoData_version_files\geology\lithoname200k
Study Area Area:     98843.25km^2
========== Starting GrandWofe ====================
Calculating weights for lithoname200k (c)...
     ...done
Result: C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT

Calculating weights for rc_appa_res (o)...
     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA

     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CD

Calculating weights for rc_dstworms (o)...
     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA

     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CD

Calculating weights for rc_magn_res4k (o)...
     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CA

     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CD

Calculating weights for rc_till_cu (o)...
     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CA

     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CD

Calculating weights for rc_till_co (o)...
     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CA

     ...done
Result: C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CD

------ Running tests... (0) ------
0: Response & Logistic Regression: lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co,C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT.dbf;C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CA.dbf

 Calculating response... 
       ...done
 Running logistic regression...
     ...done 
------ Running tests... (1) ------
1: Response & Logistic Regression: lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co,C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT.dbf;C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CD.dbf

 Calculating response... 
       ...done
 Running logistic regression...
     ...done 
------ Running tests... (2) ------
2: Response & Logistic Regression: lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co,C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT.dbf;C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CD.dbf;C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CA.dbf

 Calculating response... 
       ...done
 Running logistic regression...
     ...done 
------ Running tests... (3) ------
3: Response & Logistic Regression: lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co,C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT.dbf;C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CD.dbf;C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CD.dbf

 Calculating response... 
       ...done
 Running logistic regression...
     ...done 
------ Running tests... (4) ------
4: Response & Logistic Regression: lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co,C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT.dbf;C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CD.dbf;C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CA.dbf

 Calculating response... 
       ...done
 Running logistic regression...
     ...done 
------ Running tests... (5) ------
5: Response & Logistic Regression: lithoname200k;rc_appa_res;rc_dstworms;rc_magn_res4k;rc_till_cu;rc_till_co,C:\Users\arianne\Desktop\sdm\lithoname200k_gw1_CT.dbf;C:\Users\arianne\Desktop\sdm\rc_appa_res_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_dstworms_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_magn_res4k_gw1_CD.dbf;C:\Users\arianne\Desktop\sdm\rc_till_cu_gw1_CA.dbf;C:\Users\arianne\Desktop\sdm\rc_till_co_gw1_CD.dbf

 Calculating response... 
GP ERRORS:


Executing: CopyRaster OutRas_lyr C:\Users\arianne\Desktop\sdm\tmp\tmp_rst91 # # 255 NONE NONE # NONE NONE
Start Time: Tue Apr 24 20:25:50 2018
Succeeded at Tue Apr 24 20:25:50 2018 (Elapsed Time: 0.26 seconds)
ERROR 000582: Error occurred during execution.
Unhandled exception caught
Traceback (most recent call last):
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 212, in Execute
    gp.CopyRaster_management(RasterLayer,Temp_Raster,'#','#',NoDataArg2)
ExecuteError: ERROR 000582: Error occurred during execution.




PYTHON ERRORS:
Traceback Info:
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\grand_wofe_lr.py", line 197, in execute
    Output_MD_Variance_Raster, Output_Total_Std_Dev_Raster, Output_Confidence_Raster)

Error Info:
    <class 'arcgisscripting.ExecuteError'>: 

Executing: CopyRaster OutRas_lyr C:\Users\arianne\Desktop\sdm\tmp\tmp_rst91 # # 255 NONE NONE # NONE NONE
Start Time: Tue Apr 24 20:25:50 2018
Succeeded at Tue Apr 24 20:25:50 2018 (Elapsed Time: 0.26 seconds)
ERROR 000582: Error occurred during execution.
Unhandled exception caught
Traceback (most recent call last):
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 212, in Execute
    gp.CopyRaster_management(RasterLayer,Temp_Raster,'#','#',NoDataArg2)
ExecuteError: ERROR 000582: Error occurred during execution.





Traceback (most recent call last):
  File "<string>", line 149, in execute
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\grand_wofe_lr.py", line 197, in execute
    Output_MD_Variance_Raster, Output_Total_Std_Dev_Raster, Output_Confidence_Raster)
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\ArcSDM.pyt", line 479, in CalculateResponse
    paramUnitArea = arcpy.Parameter(
ExecuteError: 

Executing: CopyRaster OutRas_lyr C:\Users\arianne\Desktop\sdm\tmp\tmp_rst91 # # 255 NONE NONE # NONE NONE
Start Time: Tue Apr 24 20:25:50 2018
Succeeded at Tue Apr 24 20:25:50 2018 (Elapsed Time: 0.26 seconds)
ERROR 000582: Error occurred during execution.
Unhandled exception caught
Traceback (most recent call last):
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\common.py", line 45, in execute_tool
    func(self, parameters, messages)
  File "C:\Users\arianne\Desktop\Arianne data\ArcSDM-master_Jan17_Kenex\ArcSDM-master\Toolbox\arcsdm\calculateresponse.py", line 212, in Execute
    gp.CopyRaster_management(RasterLayer,Temp_Raster,'#','#',NoDataArg2)
ExecuteError: ERROR 000582: Error occurred during execution.




Cancelled function
(GrandWofe) aborted by User.
Failed at Tue Apr 24 20:25:57 2018 (Elapsed Time: 7 minutes 13 seconds)




```

**Comment by VesaNy** [comment]
I seem to be running ArcSdm 5.00.28 for ArcGis (Pro and Desktop) and you have ArcSdm 5.00.24 for ArcGis (Pro and Desktop).

**Comment by tachyon-work** [comment]
Sorry, I probably didn't update that part of the xml. Just worked on bug fixes. Expect it needs some cosmetic maintenance.

**Comment by VesaNy** [comment]
It is working now when I deleted all the old versions of the code from my computer. I am now on some infinitive loop executing calculate response and logistic regression. Was this in the original code or has this been added here?

**Comment by tachyon-work** [comment]
It is not an infinite loop. It is an annoying feature of using "ordered". 

Ordered doesn’t let you specify ascending or descending, so it produces tables for both. It is unfortunately possible to generate statistically “valid” weights tables for both _CA and _CD for the same map. So what ends up happening is that it calculates the response for every possible combination of ascending and descending tables it creates for your input maps if they are in “ordered” form. If you have 6 input maps in “ordered” form, this means 64 combinations of ascending and descending that it has to produce output maps for. You then have to actually go through them all yourself at the end and figure out which ones are actually valid. 

This is why I tweaked the Grand WofE code to allow the user to specifically define ascending or descending. It avoids this "ordered" mess. The problem always existed, I just wrote a way around it.

**Comment by VesaNy** [comment]
The valid one should be only those with studentized contrast value above 2 (or what ever you set as a threshold). This will result only either a CA or CD version, right? You then calculate the response with the right combination only once. I think this is how it worked originally. Was it wrong?

**Comment by tachyon-work** [comment]
> The valid one should be only those with studentized contrast value above 2 (or what ever you set as a threshold). This will result only either a CA or CD version, right?

Not quite. You will find that it is possible to get a valid _ca AND a valid _cd table for the same map. If you use ordered, it doesn't know which one to choose for calculate response if they are both valid. So it runs every possible combination of valid maps. 

Open up the weights tables it produced for your ordered maps. You will see that both the _ca and _cd tables Grand WofE produced for each map will have valid statistical results! It's extremely frustrating, but a statistically valid outcome.

**Comment by trotor** [comment]
I can't make this grand_wofe work in arcgis pro but am trying a lot. 

Start Time: 24 April 2018 15:05:10
Failed to execute. Parameters are not valid.
ERROR 000236: Input raster does not have an attribute table
WARNING 000970: The join field Value in the join table Band_1 is not indexed. To improve performance, we recommend that an index be created for the join field in the join table.
Failed to execute (AddJoin).
Failed at 24 April 2018 15:05:10 (Elapsed Time: 0.02 seconds)

Seems like calculate response is not able to join the tables - should it be able? I don't know what tables to try. Tried file and geodatabase versions.

**Comment by VesaNy** [comment]
You are right. Maybe I have been working previously with too perfect data sets resulting only valid CA or CD because I have not been paying attention to this. I read Gary's documentation and this issue was indeed mentioned. And it has been a long time since I have been running this tool. It seems to be running OK now on ArcGIS 10.4.1 but still failing on ArcGIS Pro. I will try that tomorrow again. It makes it much easier when we can choose to calculate either CD or  CA, not both. Good addition! Thanks.

**Comment by trotor** [comment]
This seems to be working in ArcMap but not in Arcgis pro, reference: #87

**Comment by tachyon-work** [comment]
I think so.

**Comment by smsm1920** [comment]
One small help  i need from u guys..how can i generate a 8bit unsigned integer GRID format data from a eradas generated .img format(32 BIT floating FGDBR format) as for NN tool it is important conversion.

**Comment by tachyon-work** [comment]
> One small help i need from u guys..how can i generate a 8bit unsigned integer GRID format data from a eradas generated .img format(32 BIT floating FGDBR format) as for NN tool it is important conversion.

Using the Reclassify tool in Spatial Analyst is probably easiest - just drop the filename extension at the end to save it as an ESRI grid. 

However I just want to ensure that you understand that converting a floating point grid to an integer grid (because the tool requires an integer grid so that it has an associated attribute table to work with in ArcMap) means you are going to lose information. It's unavoidable because of the way ArcMap works, so make sure you get your reclassification right :)

**Comment by smsm1920** [comment]
Thank you for your enlightenment in this regard, yes it is true in time of reclassification as it works with a range of data so over and underestimation occurs i have applied best in this regard but in ARCGIS10.3 there is no option to save it as esri grid in reclassify tool sir. An option is there by right clicking on the file then export as different format like.img , .tiff but esri grid does not work there also

**Comment by smsm1920** [comment]
Sir did u work in NN tool for any prospective mapping?

**Comment by smsm1920** [comment]
Dear sir, i have tried to apply with a demo data i got in carlin demo file in arcgis10.3 and i got this type of error. though i fixed the workspace environment. i got error below pls see
![workspace definition](https://user-images.githubusercontent.com/42085588/48393414-6f37a200-e735-11e8-8faa-9af6c5cf7f28.JPG)
![error 1](https://user-images.githubusercontent.com/42085588/48393415-6f37a200-e735-11e8-9b02-56d0d6bb8cb1.JPG)

**Comment by smsm1920** [comment]
![input environment](https://user-images.githubusercontent.com/42085588/48393434-8d050700-e735-11e8-99bf-a3045151561b.JPG)

**Comment by smsm1920** [comment]
Here is my procedure in text pls read it and if there is any wrong steps pls highlight tht.
 Wish you a very good time sir, I am a senior research scholar from a prestigious indian geophysical institute IIT(ISM). Recently i am working on mineral prospective mapping of gold and chromatite for my research. I have tried to use ArcSDM 3.1 tool to use Neural NETWORK extension but unfortunately it did not work. A brief description i am giving may be it will be helpful to understand my problem.
1. I have processed gravity magnetic and remote sensing (spectral anomaly) anomaly maps which are in .IMG(eradas imagine format) 32 bit FGDBR format.
2.I have reclassified all those out put to a same scale 0-100, also converted data to a 8bit unsingend INTEGER Format as it is important, and given fuzzy membership values and 
3.Training and non training points shape files are preapared
4. Used NN tool importing all inputs and training and non training points 
5.Error occurred , out put did not come
I have read and followed the Carlin demo as provided by you in the package there demo data was there i have tried to use that data too in NN tool but did not get any output.

Please help me . waiting for your reply
   if any manual of sdm processing is available please send . Thank you sir

**Comment by tachyon-work** [comment]
Take the space out of your folder path for the F:\SDM TEST\NN1 for a start. The tool hates any spaces in file and folder paths.

Why is anything pointing to your c:\windows folder??? That’s a big problem. Check all your environment settings. Check all your file and folder paths. 

There is no manual, but there is sufficient documentation attached to each individual tool. I run training courses on SDM on request, but not for free!

**Comment by tachyon-work** [comment]
Please refer to new thread. Closing.
